"""
Aegis – Unified Build Automation Script
========================================
Smart CLI tool that detects the host OS, presents an interactive menu,
and orchestrates PyInstaller (Desktop) or Buildozer (Mobile) builds
with correct entry points and module exclusions.

Usage
-----
    python compile.py
"""

from __future__ import annotations

import os
import platform
import shutil
import subprocess
import sys
import textwrap
from typing import Dict, List, Optional, Tuple

# ─────────────────── Constants ───────────────────────────
PROJECT_ROOT: str = os.path.dirname(os.path.abspath(__file__))
DESKTOP_ENTRY: str = "main_desktop.py"
MOBILE_ENTRY: str = "main_mobile.py"
APP_NAME: str = "Aegis"
APP_VERSION: str = "1.0.0"
ICON_PATH: str = os.path.join(PROJECT_ROOT, "assets", "logo.png")

# Colours for terminal output
CYAN = "\033[96m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
BOLD = "\033[1m"
RESET = "\033[0m"


def detect_os() -> str:
    """Detect the host operating system.

    Returns
    -------
    str
        ``'Linux'``, ``'Darwin'`` (macOS), or ``'Windows'``.
    """
    return platform.system()


def print_banner() -> None:
    """Print the Aegis build banner."""
    banner = f"""
{CYAN}{BOLD}╔══════════════════════════════════════════════╗
║          AEGIS BUILD SYSTEM v{APP_VERSION}            ║
║      End-to-End Encrypted Messenger          ║
╚══════════════════════════════════════════════╝{RESET}
"""
    print(banner)


def print_menu(options: List[str], title: str = "Select an option") -> int:
    """Display an interactive CLI menu.

    Parameters
    ----------
    options : List[str]
        Menu options.
    title : str

    Returns
    -------
    int
        Selected option index (0-based).
    """
    print(f"\n{BOLD}{title}:{RESET}")
    for i, opt in enumerate(options, 1):
        print(f"  {CYAN}[{i}]{RESET} {opt}")
    print()

    while True:
        try:
            choice = int(input(f"{GREEN}▶ Enter choice (1-{len(options)}): {RESET}"))
            if 1 <= choice <= len(options):
                return choice - 1
        except (ValueError, EOFError):
            pass
        print(f"{RED}  Invalid choice. Try again.{RESET}")


def get_desktop_formats(host_os: str) -> List[str]:
    """Return valid desktop build formats for the host OS.

    Parameters
    ----------
    host_os : str

    Returns
    -------
    List[str]
    """
    formats: Dict[str, List[str]] = {
        "Darwin": [".app (macOS Application)", ".dmg (macOS Disk Image)"],
        "Windows": [".exe (Windows Executable)"],
        "Linux": [
            ".AppImage (Linux AppImage)",
            ".deb (Debian Package)",
            "Directory Bundle",
        ],
    }
    return formats.get(host_os, ["Directory Bundle"])


def get_mobile_formats() -> List[str]:
    """Return valid mobile build formats."""
    return [".apk (Android Package)", ".aab (Android App Bundle)"]


def generate_pyinstaller_spec(
    host_os: str,
    output_format: str,
) -> str:
    """Dynamically generate a PyInstaller .spec file content.

    Targets ``main_desktop.py`` and excludes ``/ui/mobile``.

    Parameters
    ----------
    host_os : str
    output_format : str

    Returns
    -------
    str
        Contents of the .spec file.
    """
    is_onefile = "exe" in output_format.lower() or "appimage" in output_format.lower()
    icon_line = f"icon='{ICON_PATH}'," if os.path.exists(ICON_PATH) else ""

    spec = textwrap.dedent(f"""\
        # -*- mode: python ; coding: utf-8 -*-
        # Auto-generated by Aegis compile.py

        import os
        import sys

        block_cipher = None
        PROJECT_ROOT = '{PROJECT_ROOT}'

        a = Analysis(
            [os.path.join(PROJECT_ROOT, '{DESKTOP_ENTRY}')],
            pathex=[PROJECT_ROOT],
            binaries=[],
            datas=[
                (os.path.join(PROJECT_ROOT, 'assets'), 'assets'),
                (os.path.join(PROJECT_ROOT, 'ui', 'theme.kv'), os.path.join('ui')),
            ],
            hiddenimports=[
                'kivymd',
                'kivymd.uix',
                'kivymd.uix.button',
                'kivymd.uix.card',
                'kivymd.uix.label',
                'kivymd.uix.textfield',
                'kivymd.uix.boxlayout',
                'kivymd.uix.snackbar',
                'kivymd.icon_definitions',
                'cryptography',
                'cryptography.hazmat.primitives',
                'cryptography.hazmat.primitives.ciphers.aead',
            ],
            hookspath=[],
            hooksconfig={{}},
            runtime_hooks=[],
            excludes=[
                'ui.mobile',
                'ui.mobile.mobile_auth',
                'ui.mobile.mobile_chatlist',
                'ui.mobile.mobile_chatroom',
                'buildozer',
            ],
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=block_cipher,
            noarchive=False,
        )

        pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

        exe = EXE(
            pyz,
            a.scripts,
            {'a.binaries, a.zipfiles, a.datas,' if is_onefile else ''}
            [],
            exclude_binaries={'False' if is_onefile else 'True'},
            name='{APP_NAME}',
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=True,
            console=False,
            disable_windowed_traceback=False,
            argv_emulation=False,
            target_arch=None,
            codesign_identity=None,
            entitlements_file=None,
            {icon_line}
        )
    """)

    if not is_onefile:
        spec += textwrap.dedent(f"""\

        coll = COLLECT(
            exe,
            a.binaries,
            a.zipfiles,
            a.datas,
            strip=False,
            upx=True,
            upx_exclude=[],
            name='{APP_NAME}',
        )
        """)

    if host_os == "Darwin":
        spec += textwrap.dedent(f"""\

        app = BUNDLE(
            coll if 'coll' in dir() else exe,
            name='{APP_NAME}.app',
            {icon_line}
            bundle_identifier='com.aegis.messenger',
            info_plist={{
                'CFBundleName': '{APP_NAME}',
                'CFBundleDisplayName': '{APP_NAME}',
                'CFBundleVersion': '{APP_VERSION}',
                'CFBundleShortVersionString': '{APP_VERSION}',
                'NSHighResolutionCapable': 'True',
            }},
        )
        """)

    return spec


def build_desktop(host_os: str, fmt_index: int) -> None:
    """Execute a PyInstaller desktop build.

    Parameters
    ----------
    host_os : str
    fmt_index : int
    """
    formats = get_desktop_formats(host_os)
    chosen = formats[fmt_index]
    print(f"\n{CYAN}▶ Building Desktop: {chosen}{RESET}")

    # Generate spec
    spec_content = generate_pyinstaller_spec(host_os, chosen)
    spec_path = os.path.join(PROJECT_ROOT, "aegis_desktop.spec")
    with open(spec_path, "w") as f:
        f.write(spec_content)
    print(f"{GREEN}  ✓ Generated {spec_path}{RESET}")

    # Run PyInstaller
    cmd = [sys.executable, "-m", "PyInstaller", spec_path, "--clean"]
    print(f"{YELLOW}  Running: {' '.join(cmd)}{RESET}\n")
    result = subprocess.run(cmd, cwd=PROJECT_ROOT)

    if result.returncode == 0:
        print(f"\n{GREEN}{BOLD}  ✓ Desktop build complete!{RESET}")
        print(f"  Output: {os.path.join(PROJECT_ROOT, 'dist', APP_NAME)}")
    else:
        print(f"\n{RED}  ✗ Build failed with exit code {result.returncode}{RESET}")


def build_mobile(fmt_index: int) -> None:
    """Execute a Buildozer mobile build.

    Parameters
    ----------
    fmt_index : int
        0 = APK, 1 = AAB.
    """
    formats = get_mobile_formats()
    chosen = formats[fmt_index]
    print(f"\n{CYAN}▶ Building Mobile: {chosen}{RESET}")

    # Check buildozer is available
    if not shutil.which("buildozer"):
        print(f"{RED}  ✗ Buildozer not found. Install: pip install buildozer{RESET}")
        return

    # Ensure buildozer.spec points to main_mobile.py
    spec_path = os.path.join(PROJECT_ROOT, "buildozer.spec")
    if not os.path.exists(spec_path):
        print(f"{RED}  ✗ buildozer.spec not found in project root.{RESET}")
        return

    # Copy main_mobile.py → main.py for buildozer (expects main.py)
    main_backup = os.path.join(PROJECT_ROOT, "main.py")
    backup_exists = os.path.exists(main_backup)
    if backup_exists:
        shutil.copy2(main_backup, main_backup + ".bak")

    shutil.copy2(
        os.path.join(PROJECT_ROOT, MOBILE_ENTRY), main_backup
    )
    print(f"{GREEN}  ✓ Copied {MOBILE_ENTRY} → main.py{RESET}")

    # Build command
    target = "android"
    action = "debug" if fmt_index == 0 else "release"
    cmd = ["buildozer", target, action]

    print(f"{YELLOW}  Running: {' '.join(cmd)}{RESET}\n")
    result = subprocess.run(cmd, cwd=PROJECT_ROOT)

    # Restore main.py
    if backup_exists:
        shutil.move(main_backup + ".bak", main_backup)
    else:
        os.remove(main_backup)

    if result.returncode == 0:
        print(f"\n{GREEN}{BOLD}  ✓ Mobile build complete!{RESET}")
        print(f"  Output: {os.path.join(PROJECT_ROOT, 'bin')}")
    else:
        print(f"\n{RED}  ✗ Build failed with exit code {result.returncode}{RESET}")


def main() -> None:
    """Main compile.py entry point – interactive CLI."""
    print_banner()

    host_os = detect_os()
    print(f"  {BOLD}Host OS:{RESET} {host_os}")
    print(f"  {BOLD}Python:{RESET}  {sys.version.split()[0]}")
    print(f"  {BOLD}Project:{RESET} {PROJECT_ROOT}")

    # Step 1: Target UI
    ui_choice = print_menu(
        ["Desktop UI (PyInstaller)", "Mobile UI (Buildozer)"],
        title="Select Target UI",
    )

    if ui_choice == 0:
        # Desktop
        formats = get_desktop_formats(host_os)
        if not formats:
            print(f"{RED}  No desktop formats available for {host_os}.{RESET}")
            return
        fmt_choice = print_menu(formats, title="Select Output Format")
        build_desktop(host_os, fmt_choice)
    else:
        # Mobile
        if host_os == "Windows":
            print(f"{YELLOW}  ⚠ Buildozer requires Linux or macOS.{RESET}")
            print(f"  Use WSL or a Linux VM for Android builds.")
            return
        formats = get_mobile_formats()
        fmt_choice = print_menu(formats, title="Select Output Format")
        build_mobile(fmt_choice)


if __name__ == "__main__":
    main()
